name: elcm

model_type: segmented_locationchoice

segmentation_col: sector_id

choosers_fit_filters: b_year_built > 2000

choosers_predict_filters: cid == 49

alts_fit_filters:
- job_spaces > 0

alts_predict_filters: county_id == 49

interaction_predict_filters: null

choice_column: null

sample_size: 50

estimation_sample_size: 1000

default_config:
    model_expression: np.log1p(ave_nonres_price_zn) + ave_income_1500 + np.log1p(jobs_within_30_min)
        + ave_hhsize_1500

models:
    1:
        fit_parameters:
            Coefficient:
                is_other: 0.6345769403574774
                is_retail: 1.3147115512377392
                jobs_1_500: 0.9969103332105848
                jobs_9_500: -0.12053927064775873
                np.log1p(population_within_20_min): -0.47915710399875355
                np.log1p(unit_price_non_residential): 0.20719997785378474
            Std. Error:
                is_other: 0.14712785174658566
                is_retail: 0.09828757858139758
                jobs_1_500: 0.037850379895436555
                jobs_9_500: 0.023394930004046497
                np.log1p(population_within_20_min): 0.016571187876114498
                np.log1p(unit_price_non_residential): 0.028103840286513068
            T-Score:
                is_other: 4.313098660955632
                is_retail: 13.376171945765773
                jobs_1_500: 26.33818566589282
                jobs_9_500: -5.1523672277245405
                np.log1p(population_within_20_min): -28.91507281076721
                np.log1p(unit_price_non_residential): 7.372657108118397
        fitted: true
        log_likelihoods:
            convergence: -2557.335308471337
            'null': -3912.023005428176
            ratio: 0.34628827465409207
        model_expression: jobs_1_500 + is_retail + is_other + np.log1p(population_within_20_min)
            +  np.log1p(unit_price_non_residential) + jobs_9_500
        name: 1
    3:
        fit_parameters:
            Coefficient:
                jobs_200: 0.9427472950098738
                np.log1p(jobs_within_20_min_transit): 0.009029246797852887
                np.log1p(logsumpopulation): -0.6291235230359594
                np.log1p(real_far): -0.8028914243808627
                parcel_volume: -0.026489051627265038
            Std. Error:
                jobs_200: 0.028121301912874177
                np.log1p(jobs_within_20_min_transit): 0.009971703581471139
                np.log1p(logsumpopulation): 0.012309592179652743
                np.log1p(real_far): 0.06229044105010882
                parcel_volume: 0.0017107925689666301
            T-Score:
                jobs_200: 33.524311851944375
                np.log1p(jobs_within_20_min_transit): 0.9054868833677054
                np.log1p(logsumpopulation): -51.10839691958886
                np.log1p(real_far): -12.889480486018488
                parcel_volume: -15.483497010549454
        fitted: true
        log_likelihoods:
            convergence: -3031.7435587106293
            'null': -3912.023005428176
            ratio: 0.22501898518901964
        model_expression: np.log1p(real_far) + jobs_200 + np.log1p(logsumpopulation)
            + np.log1p(jobs_within_20_min_transit) + parcel_volume
        name: 3
    4:
        fit_parameters:
            Coefficient:
                is_office: 1.3325828828194488
                is_other: 0.2836994847532104
                jobs_4_500: 0.9788739457065866
                np.log1p(ave_nonres_price_zn): 0.5938681455974052
                np.log1p(jobs_5_within_10_min): -0.23528636904769687
                np.log1p(logsumpopulation): 0.15108085806925844
                np.log1p(real_far): -0.607807721938762
            Std. Error:
                is_office: 0.1067760043878056
                is_other: 0.15872917634511646
                jobs_4_500: 0.03429363069145237
                np.log1p(ave_nonres_price_zn): 0.08008421668128834
                np.log1p(jobs_5_within_10_min): 0.02404029416558001
                np.log1p(logsumpopulation): 0.03628607502885517
                np.log1p(real_far): 0.07023415262565223
            T-Score:
                is_office: 12.480171836919167
                is_other: 1.7873178157012393
                jobs_4_500: 28.543899434671676
                np.log1p(ave_nonres_price_zn): 7.4155454121606255
                np.log1p(jobs_5_within_10_min): -9.787166805328491
                np.log1p(logsumpopulation): 4.163604301350227
                np.log1p(real_far): -8.654019436646083
        fitted: true
        log_likelihoods:
            convergence: -1803.7020650311845
            'null': -3912.023005428176
            ratio: 0.5389336763796033
        model_expression: np.log1p(real_far) + np.log1p(ave_nonres_price_zn) + jobs_4_500
            + np.log1p(jobs_5_within_10_min) + is_other + is_office + np.log1p(logsumpopulation)
        name: 4
    5:
        fit_parameters:
            Coefficient:
                is_industrial: -0.14290501627703495
                is_other: -0.28672835136362784
                jobs_5_500: 1.1647781203825551
                np.log1p(ave_nonres_price_zn): 0.32650431662293233
                np.log1p(real_far): -0.2908118826518827
                parcel_volume: -0.02093176622703196
            Std. Error:
                is_industrial: 0.07302269142391321
                is_other: 0.14726909855312784
                jobs_5_500: 0.028784886217667095
                np.log1p(ave_nonres_price_zn): 0.03724047192469685
                np.log1p(real_far): 0.060010890386289956
                parcel_volume: 0.0020707257507765905
            T-Score:
                is_industrial: -1.956994647697098
                is_other: -1.9469688765711404
                jobs_5_500: 40.464920082527804
                np.log1p(ave_nonres_price_zn): 8.76745915795991
                np.log1p(real_far): -4.845985133363749
                parcel_volume: -10.108420305867089
        fitted: true
        log_likelihoods:
            convergence: -2082.6295646336116
            'null': -3912.023005428176
            ratio: 0.4676336100928259
        model_expression: np.log1p(ave_nonres_price_zn) + jobs_5_500 + is_industrial
            + is_other + np.log1p(real_far) + parcel_volume
        name: 5
    6:
        fit_parameters:
            Coefficient:
                jobs_6_500: 1.051135497835239
                np.log1p(is_office): 1.5279604470554422
                np.log1p(logsumpopulation): 0.18618431645151148
                np.log1p(real_far): -0.38526462571578274
            Std. Error:
                jobs_6_500: 0.027118390767080502
                np.log1p(is_office): 0.10655765488440999
                np.log1p(logsumpopulation): 0.011901183335182176
                np.log1p(real_far): 0.05120557218917295
            T-Score:
                jobs_6_500: 38.760983528242065
                np.log1p(is_office): 14.339283730604997
                np.log1p(logsumpopulation): 15.644185221574984
                np.log1p(real_far): -7.523880883363005
        fitted: true
        log_likelihoods:
            convergence: -2152.1720016712457
            'null': -3912.023005428176
            ratio: 0.4498570180479581
        model_expression: np.log1p(real_far) + np.log1p(is_office) + np.log1p(logsumpopulation)+jobs_6_500
        name: 6
    7:
        fit_parameters:
            Coefficient:
                jobs_7_500: 0.9437243089057749
                np.log1p(is_office): 0.006967672620961177
                np.log1p(logsumpopulation): 0.29601143162890525
                np.log1p(real_far): -0.08938828254991942
            Std. Error:
                jobs_7_500: 0.02662763172575395
                np.log1p(is_office): 0.10697506150128407
                np.log1p(logsumpopulation): 0.010705670562305715
                np.log1p(real_far): 0.04830546084407886
            T-Score:
                jobs_7_500: 35.44154127657606
                np.log1p(is_office): 0.06513361640719918
                np.log1p(logsumpopulation): 27.649966427245666
                np.log1p(real_far): -1.8504798626898178
        fitted: true
        log_likelihoods:
            convergence: -3019.319880015252
            'null': -3912.023005428176
            ratio: 0.22819475350074447
        model_expression: np.log1p(real_far) + jobs_7_500 + np.log1p(logsumpopulation)
            + np.log1p(is_office)
        name: 7
    9:
        fit_parameters:
            Coefficient:
                jobs_9_500: 1.472496437750315
                np.log1p(is_retail): 1.95981054024894
                np.log1p(logsumpopulation): -0.02917974649760142
                np.log1p(real_far): -0.14902402182646213
            Std. Error:
                jobs_9_500: 0.03674366615315945
                np.log1p(is_retail): 0.11863351941033369
                np.log1p(logsumpopulation): 0.015082978148792572
                np.log1p(real_far): 0.07196570499829293
            T-Score:
                jobs_9_500: 40.07483716002847
                np.log1p(is_retail): 16.519871870868805
                np.log1p(logsumpopulation): -1.93461438515293
                np.log1p(real_far): -2.070764426333308
        fitted: true
        log_likelihoods:
            convergence: -2257.2036600685965
            'null': -3912.023005428176
            ratio: 0.42300859250147926
        model_expression: jobs_9_500 + np.log1p(real_far) + np.log1p(is_retail) +
            np.log1p(logsumpopulation)
        name: 9
    10:
        fit_parameters:
            Coefficient:
                jobs_10_500: 1.3505015669080824
                np.log1p(population_within_10_min): -0.05017099710817625
                np.log1p(real_far): -0.33241642651107045
                sfdu_1000: -0.07421576418544681
            Std. Error:
                jobs_10_500: 0.023668793340872324
                np.log1p(population_within_10_min): 0.014063279400594271
                np.log1p(real_far): 0.06231992393381219
                sfdu_1000: 0.024471798708434172
            T-Score:
                jobs_10_500: 57.05831925854777
                np.log1p(population_within_10_min): -3.5675176236672206
                np.log1p(real_far): -5.334031326227521
                sfdu_1000: -3.032705730775256
        fitted: true
        log_likelihoods:
            convergence: -1900.5745178076345
            'null': -3912.023005428176
            ratio: 0.514170925076241
        model_expression: jobs_10_500 + np.log1p(real_far) + np.log1p(population_within_10_min)
            + sfdu_1000
        name: 10

fitted: true
